// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmaGVGZJ3RIw1G4GzbHuznw2B1K-Y5jxM',
    appId: '1:690407887505:web:45329b68f13448cd10a530',
    messagingSenderId: '690407887505',
    projectId: 'login-8172a',
    authDomain: 'login-8172a.firebaseapp.com',
    storageBucket: 'login-8172a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6aP79JpEpsdgagFDU4e7r_9KnDcWFzeM',
    appId: '1:690407887505:android:ee18d589681764c710a530',
    messagingSenderId: '690407887505',
    projectId: 'login-8172a',
    storageBucket: 'login-8172a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmaGVGZJ3RIw1G4GzbHuznw2B1K-Y5jxM',
    appId: '1:690407887505:web:0c114696420c31e410a530',
    messagingSenderId: '690407887505',
    projectId: 'login-8172a',
    authDomain: 'login-8172a.firebaseapp.com',
    storageBucket: 'login-8172a.appspot.com',
  );
}
